<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="RAVI-PC" name="com.qa.orangehrm.tests.LoginPageTest" tests="6" failures="0" timestamp="12 Jun 2020 16:41:37 GMT" time="32.129" errors="1">
  <testcase name="verifyLoginPageTitleTest" time="20.594" classname="com.qa.orangehrm.tests.LoginPageTest">
    <error type="org.openqa.selenium.TimeoutException" message="Supplied function might have stalled
Build info: version: &#039;4.0.0-alpha-5&#039;, revision: &#039;b3a0d621cc&#039;
System info: host: &#039;RAVI-PC&#039;, ip: &#039;192.168.1.3&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_91&#039;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.TimeoutException: Supplied function might have stalled
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'RAVI-PC', ip: '192.168.1.3', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:221)
at com.qa.orangehrm.util.ElementUtil.waitForTitlePresent(ElementUtil.java:41)
at com.qa.orangehrm.pages.LoginPage.getPageTitle(LoginPage.java:36)
at com.qa.orangehrm.tests.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
at java.util.concurrent.CompletableFuture.get(Unknown Source)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
... 28 more
]]>
    </error>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase name="verifyForgotpaswdLink" time="1.064" classname="com.qa.orangehrm.tests.LoginPageTest"/>
  <testcase name="verifyLoginButton" time="0.839" classname="com.qa.orangehrm.tests.LoginPageTest"/>
  <testcase name="verifySocialIcons" time="0.717" classname="com.qa.orangehrm.tests.LoginPageTest"/>
  <testcase name="loginTest" time="8.915" classname="com.qa.orangehrm.tests.LoginPageTest"/>
  <testcase name="login_invalidTestcases" classname="com.qa.orangehrm.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- login_invalidTestcases -->
</testsuite> <!-- com.qa.orangehrm.tests.LoginPageTest -->
